# import os
# import torch
# from torch.utils.data import DataLoader, Dataset
# from tqdm import tqdm
# from transformers import TrOCRProcessor, VisionEncoderDecoderModel
# from PIL import Image
# import json
# import logging
# from evaluate import load
# import sys
# from torch.cuda.amp import GradScaler, autocast # NEW: For Automatic Mixed Precision

# # === CONFIGURATION ===
# # Define paths relative to where your script will be executed on Vertex AI
# # Make sure 'output_crops' and 'line_labels.json' are in the same directory
# # or accessible from your training environment (ideally, locally staged).
# PROCESSED_DATA_DIR = "output_crops" # Where cropped images are stored
# MANIFEST_PATH = "line_labels.json"    # Generated by preparedata.py (JSON version)
# MODEL_SAVE_DIR = "../models/trocr-model" # Where the fine-tuned model will be saved
# # Path to your downloaded pretrained model snapshot.
# # This assumes the structure is PRETRAINED_MODEL_PATH/models--microsoft--trocr-base-printed/snapshots/some_hash/
# PRETRAINED_MODEL_PATH = "models/trocr-base-printed"

# BATCH_SIZE = 16 # Increased batch size, will work better with AMP
# NUM_EPOCHS = 5
# MAX_LENGTH = 128
# LEARNING_RATE = 4e-5 # Adjusted learning rate for larger batch size, fine-tune as needed
# NUM_WORKERS = 6 # Your current setting, good for 8 vCPUs
# EVAL_SAMPLES = 5 # Number of samples to evaluate for quick sanity check

# # === LOGGING SETUP ===
# logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
# logger = logging.getLogger(__name__)

# # === CUSTOM DATASET CLASS ===
# class OCRDataset(Dataset):
#     def __init__(self, manifest_path: str, processor: TrOCRProcessor):
#         self.samples = []
#         self.problematic_samples = []

#         if not os.path.exists(manifest_path):
#             logger.error(f"Manifest file not found: {manifest_path}. Please run preparedata.py first.")
#             sys.exit(1)

#         with open(manifest_path, "r", encoding="utf-8") as f:
#             data = json.load(f)
#             if not isinstance(data, list) or not all(isinstance(item, dict) and 'image_path' in item and 'text' in item for item in data):
#                 logger.error(f"Malformed JSON data in {manifest_path}. Expected a list of dictionaries with 'image_path' and 'text'.")
#                 sys.exit(1)
#             self.samples = [(item["image_path"], item["text"]) for item in data]
        
#         if not self.samples:
#             logger.error(f"No samples found in {manifest_path}. Dataset is empty.")
#             sys.exit(1)

#         self.processor = processor
#         logger.info(f"Loaded {len(self.samples)} samples from {manifest_path}.")

#     def __len__(self):
#         return len(self.samples)

#     def __getitem__(self, idx: int):
#         image_path, text = self.samples[idx]
#         try:
#             image = Image.open(image_path).convert("RGB")
#             pixel_values = self.processor(images=image, return_tensors="pt").pixel_values[0]
#             labels = self.processor.tokenizer(
#                 text,
#                 padding="max_length",
#                 truncation=True,
#                 max_length=MAX_LENGTH
#             ).input_ids
            
#             labels = torch.tensor(labels)
#             labels[labels == self.processor.tokenizer.pad_token_id] = -100
            
#             return {"pixel_values": pixel_values, "labels": labels}
#         except FileNotFoundError:
#             self.problematic_samples.append((image_path, text, "File not found"))
#             logger.warning(f"Skipping sample (idx: {idx}, image: {image_path}): Image file not found.")
#             return None
#         except Exception as e:
#             self.problematic_samples.append((image_path, text, str(e)))
#             logger.warning(f"Skipping sample (idx: {idx}, image: {image_path}): Error loading or processing image/text - {e}")
#             return None

# # === COLLATER FUNCTION ===
# def collate_fn(batch):
#     batch = [b for b in batch if b is not None]
#     if not batch:
#         return None

#     pixel_values = torch.stack([item["pixel_values"] for item in batch])
#     labels = torch.stack([item["labels"] for item in batch])
#     return {"pixel_values": pixel_values, "labels": labels}

# # === MAIN TRAINING SCRIPT ===
# def main():
#     # === DEVICE SETUP ===
#     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#     logger.info(f"Using device: {device}")
#     if device.type == 'cuda':
#         logger.info(f"CUDA device name: {torch.cuda.get_device_name(0)}")

#     # === LOAD PROCESSOR AND MODEL ===
#     # Find the actual snapshot directory within PRETRAINED_MODEL_PATH
#     actual_pretrained_path = None
#     for root, dirs, files in os.walk(PRETRAINED_MODEL_PATH):
#         # Heuristic: look for config.json and preprocessor_config.json
#         if "preprocessor_config.json" in files and "config.json" in files:
#             actual_pretrained_path = root
#             break
    
#     if actual_pretrained_path is None:
#         logger.error(f"Could not find a valid pretrained model snapshot in {PRETRAINED_MODEL_PATH}.")
#         logger.error("Please ensure your pretrained model is downloaded and accessible, e.g., 'models/trocr-base-printed/models--microsoft--trocr-base-printed/snapshots/latest_hash'.")
#         sys.exit(1)
    
#     logger.info(f"Loading processor and model from: {actual_pretrained_path}")
#     processor = TrOCRProcessor.from_pretrained(actual_pretrained_path)
#     model = VisionEncoderDecoderModel.from_pretrained(actual_pretrained_path)

#     # Configure model for generation
#     model.config.decoder_start_token_id = processor.tokenizer.cls_token_id
#     model.config.pad_token_id = processor.tokenizer.pad_token_id
#     model.config.max_length = MAX_LENGTH

#     model.to(device)
#     logger.info("Model and processor loaded successfully.")

#     # === DATA LOADING ===
#     logger.info(f"Loading dataset from manifest: {MANIFEST_PATH}")
#     dataset = OCRDataset(MANIFEST_PATH, processor)

#     train_loader = DataLoader(
#         dataset,
#         batch_size=BATCH_SIZE,
#         shuffle=True,
#         collate_fn=collate_fn,
#         num_workers=NUM_WORKERS,
#         pin_memory=torch.cuda.is_available()
#     )
#     logger.info(f"DataLoader created with batch size {BATCH_SIZE} and {NUM_WORKERS} workers.")

#     # === OPTIMIZER ===
#     optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)
#     logger.info(f"Optimizer initialized with learning rate: {LEARNING_RATE}")

#     # === NEW: GRADIENT SCALER for Automatic Mixed Precision (AMP) ===
#     scaler = GradScaler()
#     logger.info("Initialized GradScaler for Automatic Mixed Precision (AMP).")

#     # === TRAINING LOOP ===
#     logger.info("🚀 Starting training loop...")
#     model.train()

#     for epoch in range(NUM_EPOCHS):
#         epoch_loss = 0.0
#         total_batches = len(train_loader)
#         pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{NUM_EPOCHS}", total=total_batches)

#         for batch_idx, batch in enumerate(pbar):
#             if batch is None:
#                 logger.warning(f"Epoch {epoch+1}, Batch {batch_idx+1}: All samples failed, skipping batch.")
#                 continue

#             pixel_values = batch["pixel_values"].to(device)
#             labels = batch["labels"].to(device)

#             optimizer.zero_grad() # Zero gradients BEFORE autocast

#             # NEW: Forward pass with autocast for mixed precision
#             with autocast():
#                 outputs = model(pixel_values=pixel_values, labels=labels)
#                 loss = outputs.loss

#             # NEW: Scale the loss and call backward()
#             scaler.scale(loss).backward()
            
#             # NEW: Unscale gradients and call optimizer.step()
#             scaler.step(optimizer)
            
#             # NEW: Update the scaler for the next iteration
#             scaler.update()

#             epoch_loss += loss.item()
#             pbar.set_postfix({"loss": f"{loss.item():.4f}", "avg_loss": f"{epoch_loss / (batch_idx + 1):.4f}"})

#         avg_epoch_loss = epoch_loss / total_batches
#         logger.info(f"✅ Epoch {epoch+1} training complete. Average loss: {avg_epoch_loss:.4f}")

#     logger.info("Training complete.")

#     # === SAVE MODEL ===
#     logger.info(f"💾 Saving final model to: {MODEL_SAVE_DIR}")
#     os.makedirs(MODEL_SAVE_DIR, exist_ok=True)
#     model.save_pretrained(MODEL_SAVE_DIR)
#     processor.save_pretrained(MODEL_SAVE_DIR)
#     logger.info("Model and processor saved.")

#     # === EVALUATION ===
#     logger.info("📊 Starting quick evaluation on a small sample...")
#     model.eval()
#     cer_metric = load("cer")

#     preds, refs = [], []
#     evaluated_count = 0

#     for i in range(min(EVAL_SAMPLES, len(dataset))):
#         sample = dataset[i]
#         if sample is None:
#             continue

#         with torch.no_grad():
#             pixel_values = sample["pixel_values"].unsqueeze(0).to(device)
#             generated_ids = model.generate(pixel_values)
#             pred = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

#         ref = processor.tokenizer.decode(sample["labels"], skip_special_tokens=True)
#         refs.append(ref)
#         preds.append(pred)
        
#         logger.info(f"--- Sample {i+1} ---")
#         logger.info(f"GT   : {ref}")
#         logger.info(f"Pred : {pred}")
#         evaluated_count += 1
    
#     if evaluated_count > 0:
#         cer_score = cer_metric.compute(predictions=preds, references=refs)
#         logger.info(f"🎯 CER on {evaluated_count} samples: {cer_score:.4f}")
#     else:
#         logger.warning("No samples were successfully evaluated.")

#     if dataset.problematic_samples:
#         logger.warning(f"\nEncountered {len(dataset.problematic_samples)} problematic samples during data loading:")
#         for path, text, error in dataset.problematic_samples[:5]:
#             logger.warning(f"  - Image: {path}, Text: '{text[:50]}...', Error: {error}")
#         if len(dataset.problematic_samples) > 5:
#             logger.warning(f"  ...and {len(dataset.problematic_samples) - 5} more.")

# if __name__ == "__main__":
#     main()
import os
import torch
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm
from transformers import TrOCRProcessor, VisionEncoderDecoderModel
from PIL import Image
import json
import logging
from evaluate import load
import sys
from torch.cuda.amp import GradScaler, autocast # For Automatic Mixed Precision

# === CONFIGURATION ===
# Define paths relative to where your script will be executed on Vertex AI
# Make sure 'output_crops' and 'line_labels.json' are in the same directory
# or accessible from your training environment (ideally, locally staged).
PROCESSED_DATA_DIR = "output_crops" # Where cropped images are stored
MANIFEST_PATH = "line_labels.json"   # Generated by preparedata.py (JSON version)
MODEL_SAVE_DIR = "../models/trocr-model" # Where the fine-tuned model will be saved
# Path to your downloaded pretrained model snapshot.
# This assumes the structure is PRETRAINED_MODEL_PATH/models--microsoft--trocr-base-printed/snapshots/some_hash/
PRETRAINED_MODEL_PATH = "models/trocr-base-printed"

BATCH_SIZE = 8 # Increased batch size, will work better with AMP
MAX_LENGTH = 128
LEARNING_RATE = 4e-5 # Adjusted learning rate for larger batch size, fine-tune as needed
NUM_WORKERS = 6 # Your current setting, good for 8 vCPUs
EVAL_SAMPLES = 5 # Number of samples to evaluate for quick sanity check

# === NEW: For a quick test run, set a small number of samples ===
# Set this to a small number (e.g., 500 or 1000) for a test run.
# For a full training run, set this to None or a very large number (e.g., 1000000000)
# to use all available samples.
TEST_MODE_SAMPLES = None # Set to None for full training run to use all samples
NUM_EPOCHS = 2 # Start with 1 or 2 epochs for a quick test

# === LOGGING SETUP ===
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# === CUSTOM DATASET CLASS ===
class OCRDataset(Dataset):
    def __init__(self, manifest_path: str, processor: TrOCRProcessor, test_mode_samples: int = None):
        self.samples = []
        self.problematic_samples = []

        if not os.path.exists(manifest_path):
            logger.error(f"Manifest file not found: {manifest_path}. Please run preparedata.py first.")
            sys.exit(1)

        with open(manifest_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            if not isinstance(data, list) or not all(isinstance(item, dict) and 'image_path' in item and 'text' in item for item in data):
                logger.error(f"Malformed JSON data in {manifest_path}. Expected a list of dictionaries with 'image_path' and 'text'.")
                sys.exit(1)
            
            # Apply test mode filter here
            if test_mode_samples is not None:
                self.samples = [(item["image_path"], item["text"]) for item in data[:test_mode_samples]]
                logger.info(f"Loaded {len(self.samples)} samples for TEST MODE from {manifest_path}.")
            else:
                self.samples = [(item["image_path"], item["text"]) for item in data]
                logger.info(f"Loaded {len(self.samples)} samples from {manifest_path}.")
            
        if not self.samples:
            logger.error(f"No samples found in {manifest_path}. Dataset is empty.")
            sys.exit(1)

        self.processor = processor
        logger.info(f"Dataset initialized with {len(self.samples)} samples.")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx: int):
        image_path, text = self.samples[idx]
        try:
            image = Image.open(image_path).convert("RGB") # Uses image_path as is from manifest
            pixel_values = self.processor(images=image, return_tensors="pt").pixel_values[0]
            labels = self.processor.tokenizer(
                text,
                padding="max_length",
                truncation=True,
                max_length=MAX_LENGTH
            ).input_ids
            
            labels = torch.tensor(labels)
            labels[labels == self.processor.tokenizer.pad_token_id] = -100
            
            return {"pixel_values": pixel_values, "labels": labels}
        except FileNotFoundError:
            self.problematic_samples.append((image_path, text, "File not found"))
            logger.warning(f"Skipping sample (idx: {idx}, image: {image_path}): Image file not found.")
            return None
        except Exception as e:
            self.problematic_samples.append((image_path, text, str(e)))
            logger.warning(f"Skipping sample (idx: {idx}, image: {image_path}): Error loading or processing image/text - {e}")
            return None

# === COLLATER FUNCTION ===
def collate_fn(batch):
    batch = [b for b in batch if b is not None]
    if not batch:
        return None

    pixel_values = torch.stack([item["pixel_values"] for item in batch])
    labels = torch.stack([item["labels"] for item in batch])
    return {"pixel_values": pixel_values, "labels": labels}

# === MAIN TRAINING SCRIPT ===
def main():
    # === DEVICE SETUP ===
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info(f"Using device: {device}")
    if device.type == 'cuda':
        logger.info(f"CUDA device name: {torch.cuda.get_device_name(0)}")

    # === LOAD PROCESSOR AND MODEL ===
    # This section includes the os.walk logic from your original code.
    actual_pretrained_path = None
    for root, dirs, files in os.walk(PRETRAINED_MODEL_PATH):
        # Heuristic: look for config.json and preprocessor_config.json
        if "preprocessor_config.json" in files and "config.json" in files:
            actual_pretrained_path = root
            break
    
    if actual_pretrained_path is None:
        logger.error(f"Could not find a valid pretrained model snapshot in {PRETRAINED_MODEL_PATH}.")
        logger.error("Please ensure your pretrained model is downloaded and accessible, e.g., 'models/trocr-base-printed/models--microsoft--trocr-base-printed/snapshots/latest_hash'.")
        sys.exit(1)
    
    logger.info(f"Loading processor and model from: {actual_pretrained_path}")
    try:
        processor = TrOCRProcessor.from_pretrained(actual_pretrained_path)
        model = VisionEncoderDecoderModel.from_pretrained(actual_pretrained_path)
    except Exception as e:
        logger.error(f"Failed to load processor or model from {actual_pretrained_path}: {e}")
        logger.error("Error details: " + str(e))
        sys.exit(1)

    # Configure model for generation
    model.config.decoder_start_token_id = processor.tokenizer.cls_token_id
    model.config.pad_token_id = processor.tokenizer.pad_token_id
    model.config.max_length = MAX_LENGTH

    model.to(device)
    logger.info("Model and processor loaded successfully.")

    # === DATA LOADING ===
    logger.info(f"Loading dataset from manifest: {MANIFEST_PATH}")
    # Pass test_mode_samples to the dataset
    dataset = OCRDataset(MANIFEST_PATH, processor, test_mode_samples=TEST_MODE_SAMPLES)

    train_loader = DataLoader(
        dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        collate_fn=collate_fn,
        num_workers=NUM_WORKERS,
        pin_memory=torch.cuda.is_available()
    )
    logger.info(f"DataLoader created with batch size {BATCH_SIZE} and {NUM_WORKERS} workers.")

    # === OPTIMIZER ===
    optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)
    logger.info(f"Optimizer initialized with learning rate: {LEARNING_RATE}")

    # === NEW: GRADIENT SCALER for Automatic Mixed Precision (AMP) ===
    scaler = GradScaler()
    logger.info("Initialized GradScaler for Automatic Mixed Precision (AMP).")

    # === TRAINING LOOP ===
    logger.info("🚀 Starting training loop...")
    model.train()

    for epoch in range(NUM_EPOCHS):
        epoch_loss = 0.0
        total_batches = len(train_loader)
        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{NUM_EPOCHS}", total=total_batches)

        for batch_idx, batch in enumerate(pbar):
            if batch is None:
                logger.warning(f"Epoch {epoch+1}, Batch {batch_idx+1}: All samples failed, skipping batch.")
                continue

            pixel_values = batch["pixel_values"].to(device)
            labels = batch["labels"].to(device)

            optimizer.zero_grad() # Zero gradients BEFORE autocast

            # NEW: Forward pass with autocast for mixed precision
            with autocast():
                outputs = model(pixel_values=pixel_values, labels=labels)
                loss = outputs.loss

            # NEW: Scale the loss and call backward()
            scaler.scale(loss).backward()
            
            # NEW: Unscale gradients and call optimizer.step()
            scaler.step(optimizer)
            
            # NEW: Update the scaler for the next iteration
            scaler.update()

            epoch_loss += loss.item()
            pbar.set_postfix({"loss": f"{loss.item():.4f}", "avg_loss": f"{epoch_loss / (batch_idx + 1):.4f}"})

        avg_epoch_loss = epoch_loss / total_batches
        logger.info(f"✅ Epoch {epoch+1} training complete. Average loss: {avg_epoch_loss:.4f}")

    logger.info("Training complete.")

    # === SAVE MODEL ===
    logger.info(f"💾 Saving final model to: {MODEL_SAVE_DIR}")
    os.makedirs(MODEL_SAVE_DIR, exist_ok=True)
    model.save_pretrained(MODEL_SAVE_DIR)
    processor.save_pretrained(MODEL_SAVE_DIR)
    logger.info("Model and processor saved.")

    # === EVALUATION ===
    logger.info("📊 Starting quick evaluation on a small sample...")
    model.eval()
    cer_metric = load("cer")

    preds, refs = [], []
    evaluated_count = 0

    # For evaluation, create a separate dataset to get EVAL_SAMPLES regardless of training samples
    eval_dataset = OCRDataset(MANIFEST_PATH, processor, test_mode_samples=EVAL_SAMPLES)

    for i in range(min(EVAL_SAMPLES, len(eval_dataset))):
        sample = eval_dataset[i]
        if sample is None:
            continue

        with torch.no_grad():
            pixel_values = sample["pixel_values"].unsqueeze(0).to(device)
            generated_ids = model.generate(pixel_values)
            pred = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

        ref = processor.tokenizer.decode(sample["labels"], skip_special_tokens=True)
        refs.append(ref)
        preds.append(pred)
        
        logger.info(f"--- Sample {i+1} ---")
        logger.info(f"GT   : {ref}")
        logger.info(f"Pred : {pred}")
        evaluated_count += 1
    
    if evaluated_count > 0:
        cer_score = cer_metric.compute(predictions=preds, references=refs)
        logger.info(f"🎯 CER on {evaluated_count} samples: {cer_score:.4f}")
    else:
        logger.warning("No samples were successfully evaluated.")

    if dataset.problematic_samples:
        logger.warning(f"\nEncountered {len(dataset.problematic_samples)} problematic samples during data loading:")
        for path, text, error in dataset.problematic_samples[:5]:
            logger.warning(f"  - Image: {path}, Text: '{text[:50]}...', Error: {error}")
        if len(dataset.problematic_samples) > 5:
            logger.warning(f"  ...and {len(dataset.problematic_samples) - 5} more.")

if __name__ == "__main__":
    main()